{% set name = "mechanize" %}
{% set version = "0.3.1" %}
{% set sha256 = "45a207bdbf78046dd56381162526b0da09d6844ba60cf7feaad4c2816bbc7cbc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - html5lib
  run:
    - python
    - html5lib

test:
  imports:
    - mechanize

about:
  home: https://github.com/python-mechanize/mechanize  
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Stateful programmatic web browsing.'
  description: |
    Stateful programmatic web browsing in Python. Browse pages programmatically with easy HTML form filling and clicking of links.
  dev_url: https://github.com/python-mechanize/mechanize
  doc_url: https://mechanize.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
