{% set name = "mechanize" %}
{% set version = "0.4.3" %}
{% set sha256 = "d7d7068be5e1b3069575c98c870aaa96dd26603fe8c8697b470e2f65259fddbf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"


requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - html5lib >=0.999999999

test:
  imports:
    - mechanize

about:
  home: https://github.com/python-mechanize/mechanize  
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Stateful programmatic web browsing.'
  description: |
    Stateful programmatic web browsing in Python. Browse pages programmatically with easy HTML form filling and clicking of links.
  dev_url: https://github.com/python-mechanize/mechanize
  doc_url: https://mechanize.readthedocs.io

extra:
  recipe-maintainers:
    - synapticarbors
