appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hlbNAmdwGltcMkSVp3IsNVE7Hi3JBd3gtTyOqCOvgCn6yeVKG43PImUGpPiXgbZRmqDxEGiP/+N3mH/Lg2iUrVCoMpt1+uil2MgXBkY+mB5mjO1h7egCOdT4JRmaEJeoeLpXVBOv0HNdNTrAJTXkMKowlXMBQYQLFRdvN+NP6zP1RZhpgPqzpbb7xnM1KO8urZm9Q23myoh+KdItc9qyk/czq3g+frxaO3uGEAc5mm6j0Qe8hU00CV4JTdd1jVvjAbEgPXtzVg8f9cqMUfZyRWb198nibJuAVPKP+wP1eg6F9NWmaGIKN1l4vYrNpUxCTB0uXmtM22eXP75kaqFx0k7cM16XvnmPq+fiVmGbwCB5O9THcQsymLxEmyCH5sms+CqJLniBaAPDhPm2NUey3nyZJFKDXVP+rIzPchVF7vwPIjRdS1wBxs2kJ+UJu9vu/g1OMn1JV//9sEujBcCy8P0oO6g//LriM2Vd1GOolqhA91LgGwVLrG+Hzn2BkAgGzAvTBHfaH3/ItI36qLNdltZiPiT7OzANFEW8MKRxWa5BR1zAV32jDzsotIg65vZunjz9cSYbEZm8U8DjxZ3lxx1v8O9K8HvlhiNnZFdqGeL/B1AxzCbP8ofZaMehlxsmc2O7bVTZ78w+rbRabspEoStVQ7mc5nqBG6PQXIgV7l4=}
