travis:
  secure:
    BINSTAR_TOKEN: fs1RXChjnWn1EKZ2iiyC1gSfCk8DZ5RRSTCIq3wYagTtqydb7uBBqbmY47bdUZbLlygEsmiLbLbGLYwaDRehondEuUvMfJus4G1msWQw8QK8qSXeSthcEeVRTX2Pp8w3AjF0o8NZ3YuNpzNkyHo7AiLzpBsfaq3MF7Frb8AMM0l5DHGeyn4HLL8hKOjxo2J7bouNBdPsFdSk5tf9CEUrCb2qTKgt6dI+8RGvxRDHO26GY7oqwzmTpwbqwvE1SBYEkpEAReSFUogKUTt95uUG5+EX1YEgRv85e/+7H+T/gEh9dWR0qd4WbUlPibF3ry1vqnJ6p0PRGn6uVb6t+xAMPfEK+kGj0+dlVNZo+3bMRewqyP72ARa/AQ6kBahgQGxLuifWIIAJe5WYZvmFjYKIKayPgJKe5lg9UtItF6o3823EyWVTzaKkjjRbynBJW2fSft3JWqRQ7yzyizBIuZ3oDQUDxoRpbjfGXJzqTDKdFHP3hjVfW0ND80rsMSiAZ9p5tjVoAEk0VnByprBVqie8f+Ql4lnSzQ3n89Cu5g1CY+5yc2+8epmFlDUOhh3O2qSl3Pz5rLPEjHn35TuyCO9p+6oQZS6rmbyciJwZb82cxOCClLebh59fEUjuCqPdAX0X0myZ3F8cRUHzj1sFMXyb3KBQleA7CAiIcJI1ycHgiKo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
